export default {
  CHI_0_TXREQ_0: {
    elder_id: "CHI_1",
    self_id: "CHI_1",
    sent_time: 0,
    rcvd_time: 2,
    src_node: "0x0",
    tgt_node: "0x40",
    channel: "REQ",
    description: "WrDataPartial",
    address: "ADDR",
  },
  CHI_0_TXRSP_0: {
    elder_id: "CHI_1",
    self_id: "CHI_1",
    sent_time: 8,
    rcvd_time: 10,
    src_node: "0x40",
    tgt_node: "0x0",
    channel: "RSP",
    description: "CompDBID",
    address: "ADDR",
  },
  CHI_0_TXDAT_0: {
    elder_id: "CHI_1",
    self_id: "CHI_1",
    sent_time: 12,
    rcvd_time: 14,
    src_node: "0x0",
    tgt_node: "0x40",
    channel: "DAT",
    description: "CopyBackWriteData_UC",
    address: "ADDR",
  },
  CHI_0_TXRSP_1: {
    elder_id: "CHI_1",
    self_id: "CHI_1",
    sent_time: 16,
    rcvd_time: 18,
    src_node: "0x0",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },

  CHI_1_SNP_0: {
    elder_id: "CHI_1",
    self_id: "SNP_1",
    sent_time: 4,
    rcvd_time: 5,
    src_node: "0x40",
    tgt_node: "0x4",
    channel: "SNP",
    description: "SnpDataPlease",
    address: "ADDR",
  },
  CHI_1_TXRSP_0: {
    elder_id: "CHI_1",
    self_id: "SNP_1",
    sent_time: 6,
    rcvd_time: 7,
    src_node: "0x4",
    tgt_node: "0x40",
    channel: "RSP",
    description: "SnpRsp_I",
    address: "ADDR",
  },

  CHI_2_TXREQ_0: {
    elder_id: "CHI_2",
    self_id: "CHI_2",
    sent_time: 1,
    rcvd_time: 3,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "REQ",
    description: "RdUnique",
    address: "ADDR",
  },
  CHI_2_TXDAT_0: {
    elder_id: "CHI_2",
    self_id: "CHI_2",
    sent_time: 9,
    rcvd_time: 11,
    src_node: "0x40",
    tgt_node: "0x3",
    channel: "DAT",
    description: "CompData_UC",
    address: "ADDR",
  },
  CHI_2_TXRSP_0: {
    elder_id: "CHI_2",
    self_id: "CHI_2",
    sent_time: 13,
    rcvd_time: 15,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },

  CHI_3_TXRSP_0: {
    elder_id: "CHI_3",
    self_id: "CHI_3",
    sent_time: 13,
    rcvd_time: 15,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_4_TXRSP_0: {
    elder_id: "CHI_4",
    self_id: "CHI_4",
    sent_time: 14,
    rcvd_time: 16,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_5_TXRSP_0: {
    elder_id: "CHI_5",
    self_id: "CHI_5",
    sent_time: 15,
    rcvd_time: 17,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_6_TXRSP_0: {
    elder_id: "CHI_6",
    self_id: "CHI_6",
    sent_time: 16,
    rcvd_time: 18,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_7_TXRSP_0: {
    elder_id: "CHI_7",
    self_id: "CHI_7",
    sent_time: 17,
    rcvd_time: 19,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_8_TXRSP_0: {
    elder_id: "CHI_8",
    self_id: "CHI_8",
    sent_time: 18,
    rcvd_time: 20,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_9_TXRSP_0: {
    elder_id: "CHI_9",
    self_id: "CHI_9",
    sent_time: 19,
    rcvd_time: 21,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
  CHI_A_TXRSP_0: {
    elder_id: "CHI_A",
    self_id: "CHI_A",
    sent_time: 20,
    rcvd_time: 22,
    src_node: "0x3",
    tgt_node: "0x40",
    channel: "RSP",
    description: "CompAck",
    address: "ADDR",
  },
};
